import { Geist, Geist_Mono, Bebas_Neue, Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: ["400"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// const storyScript = Story_Script({
//   subsets: ["latin"],
//   weight: "400", 
//   variable: "--font-story-script",
//   display: 'swap', 
// });

export const metadata = {
  title: "Aji Setiawan Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${bebasNeue.variable}`}>
        <div className="container">
          <Navbar />
          {children}
          <Footer />   
        </div>
      </body>
    </html>
  );
}